"""Locate Datalab's machine-generated image captions inside a parsed document.

Why this exists
---------------
Datalab writes a description of every extracted figure into the markdown — as
the alt text of the image, and (almost always) again as a body paragraph right
after it. This is a documented feature of the /convert API, on by default:
`disable_image_captions` turns it off and `fence_synthetic_captions` wraps it in
HTML comments. We pass neither, so captions arrive as ordinary prose.

Measured across the 277 cached parses on this box:

  · 249 of 277 papers (90%) contain them
  · 937 captions total, 96% of them duplicated as a second body paragraph
  · 36% contain numeric values the model read off the chart, e.g.
    "MECLO 100 MG showing the highest peak score of approximately 1.15 at hour 3"
  · ~352 tokens per paper, 2.5% of all markdown

The problem is not the tokens. It is that a `source_text` quote can land inside
a sentence no author ever wrote and still pass quote verification, because the
string genuinely IS in the stored markdown. A reviewer then sees a citation
that looks like the paper and isn't. For a tool whose credibility rests on
quote-level traceability, a machine's description of a picture has to be
distinguishable from the authors' own words.

Detection is exact, not stylistic
---------------------------------
A PDF carries no alt attributes, so **any** alt text on an image in Datalab's
markdown was generated by Datalab. The alt span is therefore synthetic by
construction — nothing here guesses at what "reads machine-written", which
would inevitably misfile real author captions ("Figure 1. Time-effect curves
for pain intensity difference scores.").

The duplicate body paragraph is then found by exact string match against that
alt text. So the only way to wrongly flag author prose is for an author to have
written a passage byte-identical to Datalab's generated description — hence the
`min_duplicate_len` floor, which keeps a short alt like "Barcode" from matching
the word "barcode" occurring legitimately elsewhere.

What this deliberately does NOT do
----------------------------------
It does not modify the markdown. Offsets stay valid, the extraction prompt is
byte-identical to before, every already-stored quote still matches, and no
accuracy baseline is invalidated. The module only reports which character
ranges are synthetic; callers decide what to do with that.

Stripping the captions instead would be the wrong trade today: 36% of them
carry chart values that are genuinely useful recall, and removing them would
change extraction behaviour with no measured baseline to verify against. Label
first, decide later.
"""

from __future__ import annotations

import re
from typing import List, Optional, Sequence, Tuple

#: Markdown image: `![alt](src)`. The alt group stops at the first `]`, so alt
#: text containing parentheses — "(Y-axis, -25 to 1.25)", "(n=40)" — is captured
#: intact, and `src` (a bare filename) never contains one.
_IMAGE_RE = re.compile(r"!\[(?P<alt>[^\]]*)\]\((?P<src>[^)]*)\)")

#: Below this length an alt text is too generic to match on ("Barcode", "Logo"),
#: so its repeats are not treated as captions — only the alt span itself is.
DEFAULT_MIN_DUPLICATE_LEN = 40

Span = Tuple[int, int]
#: A caption span plus the image filename it describes.
SourcedSpan = Tuple[int, int, str]


def caption_texts(markdown: str) -> List[str]:
    """Every synthetic caption string in the document, in order of appearance."""
    if not markdown:
        return []
    return [
        alt for alt in (m.group("alt").strip() for m in _IMAGE_RE.finditer(markdown))
        if alt
    ]


def find_caption_spans_with_source(
    markdown: str,
    min_duplicate_len: int = DEFAULT_MIN_DUPLICATE_LEN,
) -> List[SourcedSpan]:
    """`(start, end, image_filename)` for every synthetic caption span.

    Covers both places a caption appears:
      1. the alt text inside `![...](...)`
      2. any exact repeat of that alt text elsewhere in the document (the
         duplicated body paragraph), when it is long enough to be unambiguous

    The filename is what makes the figure recoverable. It is the join key to the
    blocks sidecar, where the owning Figure/Picture block carries the image's
    bbox — so a caption-sourced quote can be shown against the picture it was
    actually read from, rather than against prose nobody wrote.

    Matching the *text* between the two would not work: the markdown call and
    the json/blocks call are separate Datalab generations and word their
    captions differently ("Four groups are shown" vs "Four treatment groups are
    shown" on the same figure). The filename is identical in both.

    Returns spans sorted by start. Not merged — merging would lose the
    per-span filename.
    """
    if not markdown:
        return []

    spans: List[SourcedSpan] = []
    for match in _IMAGE_RE.finditer(markdown):
        alt = match.group("alt")
        if not alt.strip():
            continue
        src = match.group("src").strip()

        # The alt span itself — offsets of group("alt") within the document.
        start, end = match.span("alt")
        spans.append((start, end, src))

        if len(alt.strip()) < min_duplicate_len:
            continue

        # Datalab repeats the caption verbatim as a body paragraph. Find every
        # other occurrence; `str.find` is exact, so nothing fuzzy slips in.
        needle = alt.strip()
        pos = markdown.find(needle)
        while pos != -1:
            spans.append((pos, pos + len(needle), src))
            pos = markdown.find(needle, pos + 1)

    return sorted(set(spans))


def find_caption_spans(
    markdown: str,
    min_duplicate_len: int = DEFAULT_MIN_DUPLICATE_LEN,
) -> List[Span]:
    """Caption character ranges only, coalesced — `(start, end)` half-open,
    sorted ascending. A view over `find_caption_spans_with_source`."""
    return _merge([
        (start, end)
        for start, end, _ in find_caption_spans_with_source(markdown, min_duplicate_len)
    ])


def caption_image_for(spans: Sequence[SourcedSpan], start: int, end: int) -> Optional[str]:
    """Filename of the image whose caption `[start, end)` falls inside.

    None when the range touches no caption, or when the caption's image has no
    filename to point at. On the rare overlap of two captions the first by
    document order wins — an arbitrary but stable choice, and a quote spanning
    two figures is not evidence for either.
    """
    if start is None or end is None or end <= start:
        return None
    for s_start, s_end, src in spans:
        if s_start >= end:
            break  # sorted by start — nothing later can overlap
        if s_end > start and src:
            return src
    return None


def overlaps_caption(spans: Sequence[Span], start: int, end: int) -> bool:
    """True if `[start, end)` intersects any caption span.

    Intersection, not containment: a quote that begins in the authors' text and
    runs into a caption is still partly machine-written, and the reviewer needs
    to know that.
    """
    if not spans or start is None or end is None or end <= start:
        return False
    for s_start, s_end in spans:
        if s_start >= end:
            break  # spans are sorted — nothing later can overlap
        if s_end > start:
            return True
    return False


def _merge(spans: List[Span]) -> List[Span]:
    """Sort and coalesce touching/overlapping ranges."""
    if not spans:
        return []
    spans = sorted(set(spans))
    merged = [spans[0]]
    for start, end in spans[1:]:
        last_start, last_end = merged[-1]
        if start <= last_end:
            merged[-1] = (last_start, max(last_end, end))
        else:
            merged.append((start, end))
    return merged
